[package]
name = "cpplab"
version = "0.1.0"
authors = ["Kelvin Ly <kelvin.ly1618@gmail.com>"]

[dependencies]
hyper = "0.7.2"
rand = "0.3.14"
wait-timeout = "0.1"

serde = "0.6"
serde_json = "0.6"
serde_macros = "0.6"

flate2 = "0.2.13"
